apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: hashicorp-vault
spec:
  secretName: vault-tls
  commonName: vault.homelab
  dnsNames:
  - vault.homelab
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
